#!/bin/sh

if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi
alias epsxe="ePSXe"
alias please="sudo"
alias vim="nvim"
alias ll='ls -alF'
alias la='exa -al --color=always --group-directories-first'
# alias cb='xsel -ib'
alias cb='xclip -selection c'
alias toggleaudio='/home/paul/scripts/toggle-audio.sh'
# alias l='ls -CF'
alias debugoff="find -name settings.py -exec sed -i 's/DEBUG\s*=\s*True/DEBUG=False/g' {} \+"
alias debugon="find -name settings.py -exec sed -i 's/DEBUG\s*=\s*False/DEBUG=True/g' {} \+"
alias dtr="find -name settings.py -exec sed -i 's/DEBUG\s*=\s*False/DEBUG=True/g' {} \+ && sudo service apache2 restart"
alias dfr="find -name settings.py -exec sed -i 's/DEBUG\s*=\s*True/DEBUG=False/g' {} \+ && sudo service apache2 restart"
alias wttr="curl wttr.in"
alias gits="git status"
alias gac="git add -u && git commit -m"
alias so="source $HOME/.zshrc"
alias sa="source $HOME/.config/aliasrc"

alias glap="git log --patch -1"
alias glp="git log --patch"
alias gcm="git commit -m"
alias gp="git push"
alias gd="git diff"
alias chx="echo 'chimken' && chmod 755"
alias fzf='fzf --reverse --prompt=">> "'
alias q='qutebrowser'

vf() { fd -H | fzf  | xargs -r $EDITOR }
vff() { fd -H . $HOME | fzf  | xargs -r $EDITOR }
# ccv() { tmp=$(fd -H -t d . $HOME | fzf) && cd $tmp }
vfc() { tmp=$( fzf ) && cd $( dirname "$tmp" ) && basename $tmp | xargs $EDITOR }
# TODO: Refactor these 
vffc() { tmpcmd=$FZF_DEFAULT_COMMAND; FZF_DEFAULT_COMMAND='fd -H . $HOME'; vfc ; FZF_DEFAULT_COMMAND=$tmpcmd }
cv() { tmp=$(fd -H -t d | fzf) && cd $tmp }
ccv() { tmp=$(fd -H -t d . $HOME | fzf) && cd $tmp }

# ZLE Bindings are useless because of the fucking terminal liitations. 
# function vf-z() { vf ; zle reset-prompt; zle redisplay; zle-keymap-select}
# zle -N vf-z
# bindkey '^f' vf-z

# function cv-z() { cv; zle reset-prompt; zle redisplay; zle-keymap-select}
# zle -N cv-z
# bindkey '^g' cv-z


# function vff-z() { vff ; zle reset-prompt; zle redisplay; zle-keymap-select}
# zle -N vff-z
# bindkey '^F' vff-z

# function ccv-z() { ccv; zle reset-prompt; zle redisplay; zle-keymap-select}
# zle -N ccv-z
# bindkey '^G' ccv-z
# Stuff that could be useful with widgets n shit
# function vf-z() { fd -H . $HOME | fzf | xargs -r $EDITOR; zle reset-prompt; zle redisplay}
# function vf-z() { vf ; zle reset-prompt; zle redisplay}
# function vf-z-f() { zle kill-whole-line; zle -U "vf\r"; zle accept-line }

# function _git-status {
#     zle kill-whole-line
#     zle -U "git status"
#     zle accept-line
# }
# zle -N _git-status
# zle -N vf-z
# zle -N vf-z-f
